CREATE TABLE `sell_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20),
	`brand` varchar(255) NOT NULL,
	`itemType` enum('tops','bottoms','outerwear','shoes','accessories') NOT NULL,
	`itemName` varchar(255) NOT NULL,
	`size` varchar(50) NOT NULL,
	`condition` enum('like_new','excellent','good','fair') NOT NULL,
	`description` text,
	`originalPrice` decimal(10,2),
	`askingPrice` decimal(10,2),
	`image1Url` text,
	`image2Url` text,
	`image3Url` text,
	`image4Url` text,
	`status` enum('pending','reviewing','accepted','rejected','completed') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`offerAmount` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sell_submissions_id` PRIMARY KEY(`id`)
);
